name: E2E scheduled run
on:
  workflow_dispatch: {}
  schedule:
    # Runs at 9:45 AM, 1:45 PM, and 4:45 PM UK time during GMT (late October to late March), excluding weekends
    - cron: "45 9,13,16 * 10-12,1-3 1-5"
    # Runs at 8:45 AM, 12:45 PM, and 3:45 PM UTC during BST (late March to late October), excluding weekends
    - cron: "15 7,8,9 * 4-9 1-5"
concurrency:
  group: ${{ github.ref }}-smoke
  cancel-in-progress: true

jobs:
  setup-and-run-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: e2e_tests
        run: npx playwright test --grep @smoke --project=chromium

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: all-blob-reports
          path: blob-report
          retention-days: 14

  merge-reports-and-upload:
    # Merge reports after playwright tests, even if some shards have failed
    if: always()
    needs: [setup-and-run-tests]
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestampid.outputs.timestamp }}
    steps:
      # We want a unique identifier to be used when we create subdirectories for our github pages with reports
      - name: Set a timestamp
        id: timestampid
        # this will store current time with UTC in outputs.timestamp (eg of value: 20231028_233147Z)
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      # we now download the reports uploaded previously to merge them and create one single html report
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-blob-reports # name of the file stored as artifact (as uploaded at the previous job)
          path: all-blob-reports # name of the folder where the download will be saved

      # Playwright will generate a report and store it inside a folder called '/playwright-report'
      - name: Merge the blobs into one single HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload full html report to artifacts for history
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-${{ steps.timestampid.outputs.timestamp }}
          path: playwright-report
          retention-days: 14